[__config__]
oldver = "nvchecker_oldver.json"
keyfile = "nvchecker_keyfile.json"

[my-package-name]
source = "github"
github = "yetone/alma-releases"
use_latest_release = true
# 或者使用正则表达式匹配 tag
# use_max_tag = true
# prefix = "v"

